package com.zerionis.log.core.model;

/**
 * Types of events generated by zerionis-log.
 *
 * Each type classifies what happened in the system. Consumers use this field
 * to group incidents, detect anomalies, and build timelines.
 *
 * Events are emitted by different components:
 * - REQUEST_*       → emitted by the Servlet Filter
 * - METHOD_*        → emitted by the AOP Aspect
 * - APPLICATION_ERROR → emitted by the ControllerAdvice
 * - SQL_*           → emitted by the SQL Interceptor
 */
public enum EventType {

    /** Start of an HTTP request. Disabled by default to avoid doubling log volume. */
    REQUEST_START,

    /** HTTP request completed successfully. Includes httpStatus and durationMs. */
    REQUEST_END,

    /** HTTP request that ended with an error (unhandled exception or 5xx status). */
    REQUEST_ERROR,

    /** Method that exceeded the configured duration threshold (default: 1000ms). */
    METHOD_SLOW,

    /** Exception thrown inside a method intercepted by AOP. */
    METHOD_ERROR,

    /** Application-level error caught by the ControllerAdvice. */
    APPLICATION_ERROR,

    /** SQL query that exceeded the configured duration threshold. */
    SQL_SLOW,

    /** SQL query that failed with an exception. */
    SQL_ERROR
}
